Fix for
```
ERROR:root:can't adapt type 'BountyFulfillment'
Traceback (most recent call last):
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: can't adapt type 'BountyFulfillment'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/gitcoin/coin/app/dashboard/notifications.py", line 443, in maybe_market_to_email
    new_bounty_acceptance(b, to_emails)
  File "/home/ubuntu/gitcoin/coin/app/marketing/mails.py", line 167, in new_bounty_acceptance
    html, text = render_new_bounty_acceptance(to_email, bounty)
  File "/home/ubuntu/gitcoin/coin/app/retail/emails.py", line 105, in render_new_bounty_acceptance
    'subscriber_id': get_or_save_email_subscriber(to_email, 'internal'),
  File "/home/ubuntu/gitcoin/coin/app/marketing/utils.py", line 46, in get_or_save_email_subscriber
    if not queryset.exists():
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/db/models/query.py", line 715, in exists
    return self.query.has_results(using=self.db)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/db/models/sql/query.py", line 509, in has_results
    return compiler.has_results()
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1032, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: can't adapt type 'BountyFulfillment'
can't adapt type 'BountyFulfillment'
============ done posting ==============
changes processed:
{   'did_bsr': False,
    'did_post_to_email': 2,
    'did_post_to_github': True,
    'did_post_to_slack': True,
    'did_post_to_twitter': False}
```